
import { Product, Category, User, FAQItem } from './types';
import { IMAGE_ASSETS } from './image-manifest';
import { PRODUCT_PRICES } from './product-prices';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'Jackets', imageUrl: IMAGE_ASSETS.categories.jackets },
  { id: 2, name: 'Sneakers', imageUrl: IMAGE_ASSETS.categories.sneakers },
  { id: 3, name: 'T-Shirts', imageUrl: IMAGE_ASSETS.categories.tShirts },
  { id: 4, name: 'Shirts', imageUrl: IMAGE_ASSETS.categories.shirts },
  { id: 5, name: 'Accessories', imageUrl: IMAGE_ASSETS.categories.accessories },
  { id: 6, name: 'Shoes', imageUrl: IMAGE_ASSETS.categories.shoes },
  { id: 7, name: 'Jeans', imageUrl: IMAGE_ASSETS.categories.jeans },
];

export const PRODUCTS: Product[] = [
  // Sneakers
  {
    id: 1,
    name: 'Tech Runner Sneakers',
    category: 'Sneakers',
    price: PRODUCT_PRICES[1],
    imageUrls: [
      IMAGE_ASSETS.products.techRunnerSneakers,
      IMAGE_ASSETS.products.techRunnerSneakers_gallery1,
      IMAGE_ASSETS.products.techRunnerSneakers_gallery2,
    ],
    description: "Designed for men who demand both style and comfort. These sneakers feature a lightweight mesh upper and a responsive sole for all-day wear.",
    fabric: "80% Polyester, 20% Elastane",
    fit: "Regular",
    care: ["Wipe clean with a damp cloth.", "Do not machine wash."],
    stock: 25,
    colors: ['Black', 'White'],
    sizes: ['8', '9', '10', '11'],
  },
  {
    id: 6,
    name: 'High-Top Canvas',
    category: 'Sneakers',
    price: PRODUCT_PRICES[6],
    imageUrls: [IMAGE_ASSETS.products.highTopCanvas],
    description: "A modern take on a classic silhouette. These high-top sneakers are built with durable canvas and a cushioned footbed for everyday comfort.",
    fabric: "100% Cotton Canvas",
    fit: "Regular",
    care: ["Spot clean only."],
    stock: 30,
    colors: ['Black', 'White', 'Red'],
    sizes: ['8', '9', '10', '11', '12'],
  },
  {
    id: 12,
    name: 'Retro Runner Sneakers',
    category: 'Sneakers',
    price: PRODUCT_PRICES[12],
    imageUrls: [IMAGE_ASSETS.products.retroRunnerSneakers],
    description: "Inspired by vintage running shoes, this pair combines suede and nylon for a retro look with modern comfort and durability.",
    fabric: "Suede, Nylon, Rubber Sole",
    fit: "Regular",
    care: ["Spot clean with a damp cloth."],
    stock: 0, // Out of stock
    colors: ['Blue', 'White'],
    sizes: ['8', '9', '10'],
  },
  {
    id: 13,
    name: 'Classic White Sneakers',
    category: 'Sneakers',
    price: PRODUCT_PRICES[13],
    imageUrls: [IMAGE_ASSETS.products.classicWhiteSneakers],
    description: "An absolute wardrobe staple. These minimalist white sneakers are crafted from faux leather for a clean, versatile look that pairs with anything.",
    fabric: "Polyurethane Upper, Rubber Sole",
    fit: "Regular",
    care: ["Wipe clean with a damp cloth."],
    stock: 50,
    colors: ['White'],
    sizes: ['7', '8', '9', '10', '11', '12'],
  },
  // Jackets
  {
    id: 2,
    name: 'Urban Explorer Jacket',
    category: 'Jackets',
    price: PRODUCT_PRICES[2],
    imageUrls: [
      IMAGE_ASSETS.products.urbanExplorerJacket,
      IMAGE_ASSETS.products.urbanExplorerJacket_gallery1,
      IMAGE_ASSETS.products.urbanExplorerJacket_gallery2,
    ],
    description: "A versatile jacket crafted for the modern explorer. Water-resistant fabric and multiple pockets make it perfect for any urban adventure.",
    fabric: "100% Nylon Shell, 100% Polyester Lining",
    fit: "Regular",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 15,
    colors: ['Black', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 5,
    name: 'Leather Biker Jacket',
    category: 'Jackets',
    price: PRODUCT_PRICES[5],
    imageUrls: [IMAGE_ASSETS.products.leatherBikerJacket],
    description: "Crafted from genuine leather, this biker jacket is an icon of rebellious style. Features asymmetrical zips and a belted waist.",
    fabric: "100% Genuine Leather",
    fit: "Slim",
    care: ["Professional leather clean only."],
    stock: 0, // Out of stock
    colors: ['Black'],
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 8,
    name: 'Tailored Wool Blazer',
    category: 'Jackets',
    price: PRODUCT_PRICES[8],
    imageUrls: [IMAGE_ASSETS.products.tailoredWoolBlazer],
    description: "Sharpen your look with this impeccably tailored wool blazer. A single-breasted design with notched lapels for a classic, polished finish.",
    fabric: "90% Wool, 10% Polyamide",
    fit: "Slim",
    care: ["Dry clean only."],
    stock: 8,
    colors: ['Black', 'Blue'],
    sizes: ['M', 'L', 'XL'],
  },
  {
    id: 11,
    name: 'Distressed Denim Jacket',
    category: 'Jackets',
    price: PRODUCT_PRICES[11],
    imageUrls: [IMAGE_ASSETS.products.distressedDenimJacket],
    description: "A timeless classic with a modern edge. This denim jacket features subtle distressing for a lived-in feel from the very first wear.",
    fabric: "100% Cotton Denim",
    fit: "Regular",
    care: ["Machine wash cold, inside out.", "Hang to dry."],
    stock: 22,
    colors: ['Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 14,
    name: 'Essential Bomber Jacket',
    category: 'Jackets',
    price: PRODUCT_PRICES[14],
    imageUrls: [IMAGE_ASSETS.products.essentialBomberJacket],
    description: "A lightweight bomber jacket that's perfect for layering. Features a ribbed collar, cuffs, and hem for a classic fit.",
    fabric: "100% Polyester",
    fit: "Regular",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 18,
    colors: ['Olive', 'Black'],
    sizes: ['M', 'L', 'XL'],
  },
  // Shirts
  {
    id: 3,
    name: 'Classic Oxford Shirt',
    category: 'Shirts',
    price: PRODUCT_PRICES[3],
    imageUrls: [
      IMAGE_ASSETS.products.classicOxfordShirt,
      IMAGE_ASSETS.products.classicOxfordShirt_gallery1,
      IMAGE_ASSETS.products.classicOxfordShirt_gallery2,
    ],
    description: "The timeless Oxford shirt, reimagined. Made from premium cotton with a modern slim fit, it’s a wardrobe essential that elevates any look.",
    fabric: "100% Premium Cotton",
    fit: "Slim",
    care: ["Machine wash warm.", "Iron on medium heat."],
    stock: 40,
    colors: ['Blue', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 15,
    name: 'Flannel Checkered Shirt',
    category: 'Shirts',
    price: PRODUCT_PRICES[15],
    imageUrls: [IMAGE_ASSETS.products.flannelCheckeredShirt],
    description: "Soft, durable, and effortlessly cool. This flannel shirt features a classic checkered pattern, perfect for a rugged, layered look.",
    fabric: "100% Cotton Flannel",
    fit: "Regular",
    care: ["Machine wash cold.", "Tumble dry medium."],
    stock: 35,
    colors: ['Red', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 16,
    name: 'Linen Casual Shirt',
    category: 'Shirts',
    price: PRODUCT_PRICES[16],
    imageUrls: [IMAGE_ASSETS.products.linenCasualShirt],
    description: "Stay cool and comfortable in this breathable linen shirt. The relaxed fit makes it ideal for warm weather and casual occasions.",
    fabric: "55% Linen, 45% Cotton",
    fit: "Relaxed",
    care: ["Machine wash cold.", "Hang to dry."],
    stock: 12,
    colors: ['White', 'Blue'],
    sizes: ['M', 'L', 'XL'],
  },
  // T-Shirts
  {
    id: 4,
    name: 'Graphic T-Shirt',
    category: 'T-Shirts',
    price: PRODUCT_PRICES[4],
    imageUrls: [IMAGE_ASSETS.products.graphicTShirt],
    description: "Make a statement with our signature graphic t-shirt. The relaxed fit and soft cotton provide ultimate comfort and style.",
    fabric: "100% Cotton",
    fit: "Regular",
    care: ["Machine wash cold with like colors.", "Hang to dry."],
    stock: 100,
    colors: ['Black', 'White'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    id: 17,
    name: 'Striped Crew Neck Tee',
    category: 'T-Shirts',
    price: PRODUCT_PRICES[17],
    imageUrls: [IMAGE_ASSETS.products.stripedCrewNeckTee],
    description: "A timeless staple, this striped t-shirt adds a touch of nautical charm to any outfit. Made from soft, breathable cotton.",
    fabric: "100% Cotton",
    fit: "Regular",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 80,
    colors: ['Blue', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 18,
    name: 'Henley Neck T-Shirt',
    category: 'T-Shirts',
    price: PRODUCT_PRICES[18],
    imageUrls: [IMAGE_ASSETS.products.henleyNeckTShirt],
    description: "A stylish alternative to the classic crew neck. This long-sleeve Henley is made from a soft waffle-knit fabric for added texture and warmth.",
    fabric: "95% Cotton, 5% Spandex",
    fit: "Slim",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 60,
    colors: ['White', 'Black'],
    sizes: ['S', 'M', 'L'],
  },
  {
    id: 24,
    name: 'Polo T-Shirt',
    category: 'T-Shirts',
    price: PRODUCT_PRICES[24],
    imageUrls: [IMAGE_ASSETS.products.poloTShirt],
    description: "A smart-casual essential. This polo shirt is made from pique cotton for a comfortable, breathable fit with a classic two-button placket.",
    fabric: "100% Cotton Pique",
    fit: "Regular",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 75,
    colors: ['Black', 'White', 'Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
  },
  // Jeans
  {
    id: 7,
    name: 'Slim Fit Jeans',
    category: 'Jeans',
    price: PRODUCT_PRICES[7],
    imageUrls: [
      IMAGE_ASSETS.products.slimFitJeans,
      IMAGE_ASSETS.products.slimFitJeans_gallery1,
      IMAGE_ASSETS.products.slimFitJeans_gallery2,
    ],
    description: "Function meets fashion. These slim fit jeans offer a modern silhouette, crafted from a durable cotton denim with a hint of stretch.",
    fabric: "98% Cotton, 2% Spandex",
    fit: "Slim",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 45,
    colors: ['Blue'],
    sizes: ['30', '32', '34', '36'],
  },
  {
    id: 19,
    name: 'Relaxed Fit Jeans',
    category: 'Jeans',
    price: PRODUCT_PRICES[19],
    imageUrls: [IMAGE_ASSETS.products.relaxedFitJeans],
    description: "For a more comfortable, casual look. These relaxed fit jeans provide extra room through the seat and thigh, without sacrificing style.",
    fabric: "100% Cotton Denim",
    fit: "Relaxed",
    care: ["Machine wash cold.", "Tumble dry low."],
    stock: 40,
    colors: ['Blue'],
    sizes: ['32', '34', '36', '38'],
  },
  {
    id: 20,
    name: 'Black Skinny Jeans',
    category: 'Jeans',
    price: PRODUCT_PRICES[20],
    imageUrls: [IMAGE_ASSETS.products.blackSkinnyJeans],
    description: "A modern essential for any wardrobe. Our skinny jeans are crafted with high-stretch denim for a sharp, clean look and all-day comfort.",
    fabric: "97% Cotton, 3% Elastane",
    fit: "Skinny",
    care: ["Machine wash cold, inside out.", "Hang to dry."],
    stock: 55,
    colors: ['Black'],
    sizes: ['28', '30', '32', '34'],
  },
  // Accessories
  {
    id: 9,
    name: 'Minimalist Leather Watch',
    category: 'Accessories',
    price: PRODUCT_PRICES[9],
    imageUrls: [IMAGE_ASSETS.products.minimalistLeatherWatch],
    description: "Elegance in simplicity. This watch features a clean, numberless dial and a genuine leather strap for a sophisticated, modern aesthetic.",
    fabric: "Stainless Steel, Genuine Leather",
    fit: "Adjustable",
    care: ["Avoid contact with water.", "Wipe with a soft cloth."],
    stock: 20,
    colors: ['Brown'],
  },
  {
    id: 21,
    name: 'Canvas Backpack',
    category: 'Accessories',
    price: PRODUCT_PRICES[21],
    imageUrls: [IMAGE_ASSETS.products.canvasBackpack],
    description: "Durable and stylish, this canvas backpack is perfect for daily commutes or weekend trips. Features a padded laptop sleeve and multiple pockets.",
    fabric: "100% Cotton Canvas, Leather Accents",
    fit: "N/A",
    care: ["Spot clean only."],
    stock: 25,
    colors: ['Olive', 'Black'],
  },
  {
    id: 22,
    name: 'Aviator Sunglasses',
    category: 'Accessories',
    price: PRODUCT_PRICES[22],
    imageUrls: [IMAGE_ASSETS.products.aviatorSunglasses],
    description: "A timeless design that never goes out of style. These aviator sunglasses feature a lightweight metal frame and polarized lenses for UV protection.",
    fabric: "Metal Alloy, Polycarbonate Lenses",
    fit: "N/A",
    care: ["Clean with lens cloth.", "Store in case."],
    stock: 30,
    colors: ['Black'],
  },
  {
    id: 26,
    name: 'Knit Beanie Hat',
    category: 'Accessories',
    price: PRODUCT_PRICES[26],
    imageUrls: [IMAGE_ASSETS.products.knitBeanieHat],
    description: "Stay warm and stylish with this classic knit beanie. Made from a soft acrylic blend for a comfortable, snug fit.",
    fabric: "100% Acrylic",
    fit: "One Size",
    care: ["Hand wash cold.", "Lay flat to dry."],
    stock: 40,
    colors: ['Black', 'Brown'],
  },
  // Shoes
  {
    id: 10,
    name: 'Suede Chelsea Boots',
    category: 'Shoes',
    price: PRODUCT_PRICES[10],
    imageUrls: [IMAGE_ASSETS.products.suedeChelseaBoots],
    description: "The perfect blend of casual and formal. Our Chelsea boots are made from rich suede with elasticated side panels for a comfortable, slip-on style.",
    fabric: "100% Suede Upper",
    fit: "Regular",
    care: ["Use a suede brush and protector spray."],
    stock: 15,
    colors: ['Brown'],
    sizes: ['8', '9', '10', '11'],
  },
  {
    id: 23,
    name: 'Leather Loafers',
    category: 'Shoes',
    price: PRODUCT_PRICES[23],
    imageUrls: [IMAGE_ASSETS.products.leatherLoafers],
    description: "Effortlessly sophisticated, these leather loafers are perfect for smart-casual occasions. Features a classic penny-slot detail and comfortable sole.",
    fabric: "100% Genuine Leather Upper",
    fit: "Regular",
    care: ["Use leather conditioner.", "Wipe clean."],
    stock: 10,
    colors: ['Black', 'Brown'],
    sizes: ['8', '9', '10'],
  },
  {
    id: 25,
    name: 'Leather Derby Shoes',
    category: 'Shoes',
    price: PRODUCT_PRICES[25],
    imageUrls: [IMAGE_ASSETS.products.leatherDerbyShoes],
    description: "A timeless formal shoe for any occasion. These Derby shoes are crafted from polished genuine leather with a durable sole and open-lacing system.",
    fabric: "100% Genuine Leather",
    fit: "Regular",
    care: ["Polish regularly.", "Use shoe trees to maintain shape."],
    stock: 20,
    colors: ['Black', 'Brown'],
    sizes: ['8', '9', '10', '11'],
  }
];

// This is a mock database. In a real application, this would be a secure backend service.
export const USERS: User[] = [
  {
    id: 1,
    name: "Alex Mercer",
    email: "alex.mercer@example.com",
    password: "password123", // NOTE: Passwords should NEVER be stored in plaintext. This is for demo purposes only.
    memberSince: "June 2023",
    role: 'customer',
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    password: "password456",
    memberSince: "July 2023",
    role: 'customer',
  }
];


export const FAQS: FAQItem[] = [
  {
    question: "What is your shipping policy?",
    answer: "We offer free standard shipping on all orders above ₹999. For orders below this amount, a flat rate of ₹50 applies. Express shipping is also available at an additional cost. Standard shipping typically takes 3-5 business days within India."
  },
  {
    question: "How can I track my order?",
    answer: "Once your order has shipped, you will receive an email with a tracking number and a link to our 'Order Tracking' page. You can enter your order ID on that page to see the latest updates on your delivery."
  },
  {
    question: "What is your return policy?",
    answer: "We offer 7-Day Easy Returns. Items must be in their original condition, unworn, and with all tags attached. To initiate a return, please visit our 'Returns' page or contact our support team."
  },
  {
    question: "How do I know what size to order?",
    answer: "Each product page includes a detailed 'Fit' description (e.g., Slim, Regular, Oversized). We recommend comparing these details to a similar item you already own to find the perfect size."
  },
  {
    question: "What payment methods do you accept?",
    answer: "We accept all major credit cards (Visa, MasterCard), UPI, and Cash on Delivery (COD). All transactions are secure and encrypted."
  }
];
